name: Tracker Auto Sync

on:
  schedule:
    - cron: '* * * * *' # شغّل السكربت كل دقيقة
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: npm install

      - name: Run Tracker Sync
        run: node index.js
